# This file is the entry point to configure your own services.

parameters:

services:
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances
        autoconfigure: true # Enregistre automatiquement les services comme commandes, subscribers, etc.
        public: false       # Les services sont privés par défaut

    # Services par défaut pour tout le dossier src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Handlers de connexion
    App\Security\LoginSuccessHandler: ~
    App\Security\LoginFailureHandler: ~

    # Définition de ton extracteur JWT pour le cookie (LexikJWT)
    App\Security\JwtCookieExtractor:
        tags:
            - { name: lexik_jwt_authentication.extractor }
